---
KOHA_API_USERNAME: "{{ vault_koha_api_username }}"
KOHA_API_PASSWORD: "{{ vault_koha_api_password }}"
OAUTH2_CLIENT_SECRET: "{{ vault_oauth2_client_secret }}"
KOHA_PWRESET_API_KEY: "{{ vault_koha_pwreset_api_key }}"
SECRET_KEY_BASE: "{{ vault_secret_key_base }}"
